name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write          # required for deploy-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ check out your code
      - uses: actions/checkout@v4

      # 2 ▸ set up Node (with caching)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3 ▸ install deps & build the site
      - run: npm ci
      - run: npm run build          # Vite outputs to ./dist

      # 4 ▸ configure the GitHub Pages env
      - uses: actions/configure-pages@v4

      # 5 ▸ upload the built files (✅ correct Pages action)
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

      # 6 ▸ deploy to Pages
      - uses: actions/deploy-pages@v2
