name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write          # required for deploy-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1 ▸ Check out the code
      - uses: actions/checkout@v4

      # 2 ▸ Set up Node (with npm cache)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3 ▸ Install dependencies & build with Vite
      - run: npm ci
      - run: npm run build              # Vite outputs ./dist

      # 4 ▸ Configure the GitHub Pages environment  (stable v3)
      - uses: actions/configure-pages@v3

      # 5 ▸ Upload the built site       (stable v1)
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      # 6 ▸ Deploy to GitHub Pages      (stable v1)
      - id: deployment
        uses: actions/deploy-pages@v1
